configs:
  - name: "service-mesh"
    composite_keys: [ "destination_asset_id" ]
    metric_configs:
      - metric: "error_rate"
    unified_config:
      unified_metric_name: "service_mesh_unified_anomaly"
      unified_metrics: [ "error_rate" ]
  - name: "service-mesh-s2s"
    composite_keys: ["source_asset_id, destination_asset_id"]
    metric_configs:
      - metric: "error_rate"
    unified_config:
      unified_metric_name: "service_mesh_s2s_unified_anomaly"
      unified_metrics: [ "error_rate" ]
  - name: "default-argorollouts"
    composite_keys: [ "namespace", "name", "app", "rollouts_pod_template_hash" ]
    metric_configs:
      - metric: "namespace_app_rollouts_http_request_error_rate"
        static_threshold: 3
        static_threshold_wt: 0.7
      - metric: "namespace_app_rollouts_http_request_latency"
        static_threshold: 3
    unified_configs:
      unified_metric_name: "namespace_app_rollouts_unified_anomaly"
      unified_metrics: [ "namespace_app_rollouts_http_request_error_rate",
                           "namespace_app_rollouts_http_request_latency" ]
  - name: "default-argocd"
    composite_keys: [ "namespace", "name" ]
    metric_configs:
      - metric: "namespace_app_http_server_requests_errors"
        static_threshold: 3
      - metric: "namespace_app_http_server_requests_error_rate"
        static_threshold: 3
      - metric: "namespace_app_http_server_requests_latency"
        static_threshold: 3
      - metric: "namespace_app_cpu_utilization"
        static_threshold: 80
      - metric: "namespace_app_memory_utilization"
        static_threshold: 80
    unified_config:
      unified_metric_name: "namespace_app_unified_anomaly"
      unified_metrics: [ "namespace_app_http_server_requests_errors",
                           "namespace_app_http_server_requests_error_rate",
                           "namespace_app_http_server_requests_latency",
                           "namespace_app_cpu_utilization",
                           "namespace_app_memory_utilization" ]
